ShareNote/ShareNote/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("notes/",include("note.urls")),
    path("diagram/",include("diagram.urls")),
    path("authApp/",include("authApp.urls")),
    path("temps/",include("temps.urls"))
]

ShareNote/authApp/urls.py
from django.urls import path
from . import views 
app_name="authApp"
urlpatterns = [
    path("",views.home,name="home"),
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("resetPasswordPage/", views.resetPasswordPage, name="resetPasswordPage"),
    path('forgotPasswordPage/', views.forgotPasswordPage, name="forgotPasswordPage"),
    path('passFortgot/', views.PassForgot, name="passForgot"),
   path('note-suggestions/', views.note_suggestions, name='note_suggestions'),
]

ShareNote/diagram/urls.py
from django.urls import path
from . import views 
app_name="diagram"
urlpatterns = [
    path("",views.view_diagram,name="view_diagram"),
    path("create",views.create_diagram,name="create_diagram"),
    path("<int:diagram_id>",views.edit_diagram,name="edit_diagram"),
    path("delete/<int:diagram_id>",views.delete_diagram,name="delete_diagram")
  
]

ShareNote/note/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views 
app_name="note"
urlpatterns = [
    path("", views.view_notes, name="view_notes"),
    path("create_note_form/", views.create_note_form, name="create_note_form"),
    path("create/", views.create_notes, name="create_notes"),
    path("add_collabs", views.add_collabs, name="add_collabs"),
    path("main/<int:note_id>/<str:error>", views.edit_note_form_m, name="edit_note_form_m"),
    path("main_edit/<int:note_id>/", views.edit_notes_m, name="edit_notes_m"),

    path("collab/<int:note_id>", views.edit_note_form_c, name="edit_note_form_c"),
    path("collab_edit/<int:note_id>/", views.edit_notes_c, name="edit_notes_c"),

    path("note/<int:note_id>", views.see_perticular_note, name="see_perticular_note"),

    path("delete_media/<int:media_id>/", views.delete_media, name="delete_media"),
    path("delete_note/<int:note_id>/", views.delete_note, name="delete_note"),
    path("delete_collab/<int:c_id>/", views.delete_collab, name="delete_collab"),


    path("daily_schedule/<int:note_id>/", views.daily_schedule, name="daily_schedule"),
    path("templatesave/<int:note_id>/<int:template_id>/", views.templatesave, name='template_save'),
    path("get_existing_rows/<int:note_id>/<int:template_id>/", views.get_existing_rows, name='get_existing_rows'),

    
    path("week_schedule/<int:note_id>/", views.week_schedule, name="week_schedule"),
    path("todo/<int:note_id>/", views.todo, name="todo"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ShareNote/diagram/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.


class Diagram(models.Model):
    title = models.CharField(max_length=64)
    content = models.TextField()
    createdBy = models.ForeignKey(User,on_delete=models.CASCADE,related_name="CreatorOfDiagram")
    version = models.IntegerField()
    lastModified = models.DateTimeField()

    # we store shape as json format then at rendering time we use draw.io js library to render the diagram from json format 

ShareNote/diagram/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.http import HttpResponse
from authApp.apps import AuthConfig
from django.contrib.auth.models import User
from .models  import Diagram
from datetime import datetime
#Create your views here.
def view_diagram(request):
    diagrams = request.user.CreatorOfDiagram.all()
    print(diagrams)
    return render(request,'diagram/view_diagram.html',{ "diagrams":diagrams})


def create_diagram(request):
    if request.method == 'POST':
          title = request.POST.get('title')
          content = request.POST.get('content')
          version = request.POST.get('version')
          diagram = Diagram(title=title,content=content,createdBy=request.user,version=version,lastModified=datetime.now())
          diagram.save()
          return redirect("/authApp/")

    return render(request,'diagram/create_diagram.html')

def edit_diagram(request,diagram_id):
    diagram_obj = Diagram.objects.get(id=diagram_id)
    diagram_obj.version += 1
    if request.method == 'POST':
          diagram_obj.title = request.POST.get('title')
          diagram_obj.label = request.POST.get('label')
          diagram_obj.content = request.POST.get('content')
          diagram_obj.version = request.POST.get('version')
          diagram_obj.save()
          print("diagram changes saved in db")
          return redirect("/authApp/")
    else :
         return render(request,"diagram/edit_diagram.html",{"diagram":diagram_obj})


def delete_diagram(request, diagram_id):
    d = Diagram.objects.get(pk = diagram_id)
    d.delete()
    return redirect('diagram:view_diagram')

ShareNote/diagram/templates/diagram/create_diagram.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>diagram maker</title>
        <style>
            div#container{
                display: flex;
                flex-direction: row;

            }
            div#diagram-canvas{
                 width: 70%;
                 height: 35rem;
                 border: 2px solid black;
            }
            div#object-list{
                width: 25%;
                height: 35rem;
                border: 2px solid black;
                margin-left: 10px;
                
            }
            div img
            {
                width: 130px;
                height: 90px;
            }
            input#title{
                height: 17px;
                margin-top: 10px;
                margin-bottom: 10px
            }
            label
            {
                color: black;
                border-radius: 10px;
                font-size: large;
                padding: 5px;
                font-family: 'Courier New', Courier, monospace;
                font-weight: bolder;
            }
            #option_container{
               display: flex;
               flex-direction: row;
               justify-content: space-around;
            }
            .options
            {
                margin-top: 10px;
                margin-bottom: 10px;
                font-size: larger;
                color: aliceblue;
                background-color: blue;
                border-radius: 10px;
                padding: 5px;
            }
            .btn
            {
                 font-size: larger;
                 font-weight: bolder;
                 color: aliceblue;
                 background-color: blue;
                 border-radius: 10px;
                 padding: 5px;
                 margin-right: 10px;
            }
        </style>
    </head>
  
<body>
   
    <!-- content -->
    <form action="" method="post">
    {% csrf_token %}
<center>
     <button type="submit" class="btn">home</button>
     <label for="title">title-name</label>
     <input type="text" placeholder="title" name="title" id="title">
     
</center>
   
    <input type="hidden" name="version" value="1">
    <input type="hidden" name="content" value="" id="content">
<div id="container">
    <div id="diagram-canvas">

    </div>
    <div id="object-list">
      <div id="rectangle" onclick="addRectTOdiagram()"><img src="{% static 'diagram/imgs/rectangle.png' %}" alt="" srcset=""></div>
      <div id="circle" onclick="addCircleTOdiagram()"><img src="{% static 'diagram/imgs/circle.png'%}" alt="" srcset=""></div>
      <div id="diamond" onclick="addDiamondTOdiagram()"><img src="{% static 'diagram/imgs/polygon.png'%}" alt="" srcset=""></div>
      <div id="ellipse" onclick="addEllipseTOdiagram()"><img src="{% static 'diagram/imgs/elipse.png'%}" alt="" srcset=""></div>
      <div id="link" onclick="addLinkTOdiagram()"><img src="{% static 'diagram/imgs/link.png' %}" alt="" srcset=""></div>
      <div id="doublelink" onclick="addDlinkTOdiagram()"><img src="{% static 'diagram/imgs/Dlink.png' %}" alt="" srcset=""> </div>
    </div>
</div>
    <!-- dependencies -->
    <script src="https://cdn.jsdelivr.net/npm/@joint/core@4.0.1/dist/joint.js"></script>
    <script src="{% static 'diagram/js/main.js' %}"></script>
<div id="option_container">
    <div onclick="rotate()" class="options">rotate</div>
    <div onclick="change_color()" class="options">change color</div>
    <div onclick="change_text()" class="options">change text</div>
    <div onclick="delete_element()" class="options">delete</div>
    <div onclick="set_content()" class="options">save</div>
</div>
    

</form>
</body>
</html>

ShareNote/diagram/templates/diagram/edit_diagram.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>diagram maker</title>
        <style>
            div#container{
                display: flex;
                flex-direction: row;

            }
            div#diagram-canvas{
                 width: 70%;
                 height: 35rem;
                 border: 2px solid black;
            }
            div#object-list{
                width: 25%;
                height: 35rem;
                border: 2px solid black;
                margin-left: 10px;
                
            }
            div img
            {
                width: 130px;
                height: 90px;
            }
            input#title{
                height: 17px;
                margin-top: 10px;
                margin-bottom: 10px
            }
            label
            {
                color: black;
                border-radius: 10px;
                font-size: large;
                padding: 5px;
                font-family: 'Courier New', Courier, monospace;
                font-weight: bolder;
            }
            #option_container{
               display: flex;
               flex-direction: row;
               justify-content: space-around;
            }
            .options
            {
                margin-top: 10px;
                margin-bottom: 10px;
                font-size: larger;
                color: aliceblue;
                background-color: blue;
                border-radius: 10px;
                padding: 5px;
            }
            .btn
            {
                 font-size: larger;
                 font-weight: bolder;
                 color: aliceblue;
                 background-color: blue;
                 border-radius: 10px;
                 padding: 5px;
                 margin-right: 10px;
            }

        </style>
    </head>
  
<body>
   
    <!-- content -->
    <form action="" method="post">
    {% csrf_token %}
    <center>
        <button type="submit" class="btn">home</button>
        <label for="title">title-name</label>
        <input type="text" placeholder="title" name="title" id="title" value="{{diagram.title}}">
   </center>
    <input type="hidden" name="version" value="{{diagram.version}}">
    <input type="hidden" name="content" value="{{diagram.content}}" id="content">
<div id="container">
    <div id="diagram-canvas">

    </div>
    <div id="object-list">
      <div id="rectangle" onclick="addRectTOdiagram()"><img src="{% static 'diagram/imgs/rectangle.png' %}" alt="" srcset=""></div>
      <div id="circle" onclick="addCircleTOdiagram()"><img src="{% static 'diagram/imgs/circle.png'%}" alt="" srcset=""></div>
      <div id="diamond" onclick="addDiamondTOdiagram()"><img src="{% static 'diagram/imgs/polygon.png'%}" alt="" srcset=""></div>
      <div id="ellipse" onclick="addEllipseTOdiagram()"><img src="{% static 'diagram/imgs/elipse.png'%}" alt="" srcset=""></div>
      <div id="link" onclick="addLinkTOdiagram()"><img src="{% static 'diagram/imgs/link.png' %}" alt="" srcset=""></div>
      <div id="doublelink" onclick="addDlinkTOdiagram()"><img src="{% static 'diagram/imgs/Dlink.png' %}" alt="" srcset=""> </div>
    </div>
</div>
    <!-- dependencies -->
    <script src="https://cdn.jsdelivr.net/npm/@joint/core@4.0.1/dist/joint.js"></script>
    <script src="{% static 'diagram/js/main.js' %}"></script>
    <div id="option_container">
        <div onclick="rotate()" class="options">rotate</div>
        <div onclick="change_color()" class="options">change color</div>
        <div onclick="change_text()" class="options">change text</div>
        <div onclick="delete_element()" class="options">delete</div>
        <div onclick="set_content()" class="options">save</div>
    </div>
</form>
</body>
</html>

ShareNote/diagram/templates/diagram/view_diagram.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>view diagram</title>
 <style>
      div.diagram-container{
        border:2px solid black;
        margin-top: 10px;
        margin-bottom: 10px;
      }
      div.outer-container{
        border:2px solid black;
        margin-bottom:10px;
        margin-top:10px;
      }
      .title{
        font-size: large;
        font-family: Arial, Helvetica, sans-serif;
      }
      .btns{
        margin: 15px;
        border: 2px solid white;
        background-color: blue;
        color: white;
        text-decoration: none;
        font-size: large;
        padding: 5px;
        border-radius: 10px;
        
      }
 </style>
<script> 
// function to render the diagram // 
var str;
var graph;
var paper;
function render(str,graph)
{
     let JsonOfString = JSON.parse(str)
     graph.fromJSON(JsonOfString);
}
 
</script> 
<script src="https://cdn.jsdelivr.net/npm/@joint/core@4.0.1/dist/joint.js"></script>
</head>
<body>
        <a href="{% url 'diagram:create_diagram' %}" class="btns">create new diagram</a>
    <a href="{% url 'authApp:home' %}" class="btns">back to home</a>
    {% for diagram in diagrams %}
<center>
<div class="outer-container">
    <p class="title">Title : {{diagram.title}}</p>
    <a href="{{diagram.id}}" class="btns">edit</a>
    <a href="delete/{{diagram.id}}" class="btns">delete</a>
    <a href="#" onclick="downloadDiagram({{diagram.id}})" class="btns">download as jpeg</a>
    <div id="diagram-container-{{diagram.id}}" width="500" height="500" class="diagram-container">
    <script>
             str = "{{diagram.content}}";
             str  = str.replace(/&quot;/g, '"').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&')
             graph = new joint.dia.Graph();
             paper = new joint.dia.Paper({
             el: document.getElementById('diagram-container-{{diagram.id}}'),
             model: graph,
             width: 800,
             height: 600,
             interactive : false,
       });
       render(str,graph);
    </script>
    </div>
</div>
</center>
    {% endfor %}
</body>
<script src="../../static/diagram/js/main.js"></script>
</html>