ShareNote/ShareNote/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("notes/",include("note.urls")),
    path("diagram/",include("diagram.urls")),
    path("authApp/",include("authApp.urls")),
    path("temps/",include("temps.urls"))
]

ShareNote/authApp/urls.py
from django.urls import path
from . import views 
app_name="authApp"
urlpatterns = [
    path("",views.home,name="home"),
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("resetPasswordPage/", views.resetPasswordPage, name="resetPasswordPage"),
    path('forgotPasswordPage/', views.forgotPasswordPage, name="forgotPasswordPage"),
    path('passFortgot/', views.PassForgot, name="passForgot"),
   path('note-suggestions/', views.note_suggestions, name='note_suggestions'),
]

ShareNote/note/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views 
app_name="note"
urlpatterns = [
    path("", views.view_notes, name="view_notes"),
    path("create_note_form/", views.create_note_form, name="create_note_form"),
    path("create/", views.create_notes, name="create_notes"),
    path("add_collabs", views.add_collabs, name="add_collabs"),
    path("main/<int:note_id>/<str:error>", views.edit_note_form_m, name="edit_note_form_m"),
    path("main_edit/<int:note_id>/", views.edit_notes_m, name="edit_notes_m"),

    path("collab/<int:note_id>", views.edit_note_form_c, name="edit_note_form_c"),
    path("collab_edit/<int:note_id>/", views.edit_notes_c, name="edit_notes_c"),

    path("note/<int:note_id>", views.see_perticular_note, name="see_perticular_note"),

    path("delete_media/<int:media_id>/", views.delete_media, name="delete_media"),
    path("delete_note/<int:note_id>/", views.delete_note, name="delete_note"),
    path("delete_collab/<int:c_id>/", views.delete_collab, name="delete_collab"),


    path("daily_schedule/<int:note_id>/", views.daily_schedule, name="daily_schedule"),
    path("templatesave/<int:note_id>/<int:template_id>/", views.templatesave, name='template_save'),
    path("get_existing_rows/<int:note_id>/<int:template_id>/", views.get_existing_rows, name='get_existing_rows'),

    
    path("week_schedule/<int:note_id>/", views.week_schedule, name="week_schedule"),
    path("todo/<int:note_id>/", views.todo, name="todo"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ShareNote/note/models.py
from django.db import models
from django.contrib.auth.models import User 
# Create your models here.

class Template(models.Model):
    title = models.CharField(max_length=64)
    content = models.TextField()
    createdBy = models.ForeignKey(User,on_delete=models.CASCADE,related_name="CreatorOfTemplate")

class Note(models.Model):
    title = models.CharField(max_length=64)
    createdBy = models.ForeignKey(User,on_delete=models.CASCADE,related_name="creator")
    label = models.CharField(max_length=64)
    version = models.IntegerField()
    lastModified = models.DateTimeField()
    modifications = models.TextField(default=None)
    templateUsed = models.ForeignKey(Template,default=None,on_delete=models.CASCADE,related_name="TemplateUsedis", null=True)

class Media(models.Model):
    media_type = models.CharField(max_length=64)
    details = models.CharField(max_length=64)
    belong_to = models.ForeignKey(Note,on_delete=models.CASCADE,default=None)


class Text(models.Model):
    data = models.TextField()
    style = models.CharField(max_length=64)
    IsBold = models.BooleanField(default=False)
    IsItalic = models.BooleanField(default=False)
    IsUnderline = models.BooleanField(default=False)
    align = models.CharField(max_length=64)
    belong_to = models.ForeignKey(Note,default=None,on_delete=models.CASCADE)

    
class collabs(models.Model):
    note_id=models.ForeignKey(Note,on_delete=models.CASCADE)
    user_id=models.ForeignKey(User,on_delete=models.CASCADE)
    permission=models.CharField(max_length=50)

ShareNote/note/views.py
import datetime
import json
import os
from time import timezone
from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.models import User
from .models import Media, Note,Text,collabs, Template
from django.contrib.auth.decorators import login_required
from django import forms
from django.conf import settings
from django.core.mail import send_mail
# Create your views here.

@login_required
def templatesave(request, note_id, template_id):
    if request.method == 'POST':
        try:
            note = Note.objects.get(id=note_id)
            template = Template.objects.get(id=template_id)
            data = json.loads(request.body)
            content = json.dumps(data)  # Convert data back to JSON string
            template.content = content
            template.save()
            print(data)
            print(content)
            return JsonResponse({'success': True})
        except Exception as e:
            return JsonResponse({'success': False, 'error': str(e)})
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request method'})


@login_required
def get_existing_rows(request, note_id, template_id):
    try:
        template = Template.objects.get(id=template_id)
        content = template.content  # Assuming content is stored as JSON in the template model
        existing_rows = json.loads(content)
        return JsonResponse({'success': True, 'rows': existing_rows})
    except Template.DoesNotExist:
        return JsonResponse({'success': False, 'error': 'Template not found'})
    except Exception as e:
        return JsonResponse({'success': False, 'error': str(e)})
    

@login_required
def daily_schedule(request, note_id):
    note = Note.objects.get(id=note_id)
    return render(request, "note/Daily_Schedule.html", {'note':note})

@login_required
def week_schedule(request, note_id):
    note = Note.objects.get(id=note_id)
    return render(request, "note/week_Schedule.html", {'note':note})

@login_required
def todo(request, note_id):
    note = Note.objects.get(id=note_id)
    return render(request, "note/To_Do.html", {'note':note})


@login_required
def see_perticular_note(request, note_id):
    note = get_object_or_404(Note, id=note_id)
    media = Media.objects.filter(belong_to=note)
    text = Text.objects.filter(belong_to=note)
    collab = collabs.objects.filter(note_id=note)
    return render(request, "note/see_note.html", {"note": note, "media": media, "text": text, "collab": collab})



@login_required
def create_note_form(request):
    users = User.objects.all()
    return render(request, "note/create_note.html", {'users' : users})

    
@login_required
def edit_note_form_m(request, note_id, error=None):
    note_with_text = Note.objects.get(id=note_id)
    media = Media.objects.filter(belong_to=note_id)
    text = Text.objects.filter(belong_to=note_id)
    collab = collabs.objects.filter(note_id = note_with_text)
    print(text)
    print(media)
    print(collab)
    return render(request, "note/edit.html", {"note": note_with_text, "media": media, "text": text, "collab": collab, "error": error})

@login_required
def edit_note_form_c(request, note_id):
    note_with_text = Note.objects.get(id=note_id)
    media = Media.objects.filter(belong_to=note_id)
    text = Text.objects.filter(belong_to=note_id)
    print(text)
    print(media)
    return render(request, "note/edit_collab.html", {"note": note_with_text, "media": media, "text": text})


@login_required
def edit_notes_c(request, note_id):
    if request.method == 'POST':
        note = get_object_or_404(Note, pk=note_id)
        note.lastModified = datetime.datetime.now()
        version = note.version
        note.version = version + 1
        note.modifications += f"\nLast modified by collaborator {request.user.username} at time  {note.lastModified}"
        # Update other attributes of the note as needed
        note.save()


        # Update related Text object(s)
        text_data = request.POST.get('data')
        is_bold = request.POST.get('IsBold') == '1'
        is_italic = request.POST.get('IsItalic') == '1'
        is_underline = request.POST.get('IsUnderline') == '1'
        align = request.POST.get('align')
        style = request.POST['style']
        texts = Text.objects.filter(belong_to=note)
        for text in texts:
            text.data = text_data
            text.IsBold = is_bold
            text.IsItalic = is_italic
            text.IsUnderline = is_underline
            text.align = align
            text.style = style
            # Update other attributes of Text object as needed
            text.save()

        # Update related Media object
        media_type = request.POST.get("media_type")
        if media_type:
            details = request.FILES.get('details')
            if details:
                media_folder = os.path.join(settings.MEDIA_ROOT, 'medias')
                if not os.path.exists(media_folder):
                    os.makedirs(media_folder)

                media_path = os.path.join(media_folder, details.name)
                with open(media_path, 'wb+') as destination:
                    for chunk in details.chunks():
                        destination.write(chunk)

                # Create or update Media object
                Media.objects.create(media_type=media_type, details=os.path.join('medias', details.name), belong_to=note)

        # Call function to send email to note creator
        modification = datetime.datetime.now()
        subject = 'Edit note by collaborator'
        message = f"""\
Title: {note.title}
Collaborator: {request.user.username}
Modification Time: {modification}
Version: {version}

Dear {note.createdBy.username},

We would like to inform you that your note has been edited by collaborator {request.user.username} 
at {modification}. The note is now in version {version}.

Best regards,
Your Collaborator
"""
        email_from = settings.EMAIL_HOST_USER
        recipient_email = [note.createdBy.email]  # Assuming createdBy is a User instance with email field
        send_mail(subject, message, email_from, recipient_email)


    return redirect('note:view_notes')




@login_required
def edit_notes_m(request, note_id):
    if request.method == 'POST':
        note = get_object_or_404(Note, pk=note_id)
        note.title = request.POST['title']
        note.label = request.POST['label']
        note.lastModified = datetime.datetime.now()
        version = note.version
        note.version = version + 1
        note.modifications += f"\nLast modified by {note.createdBy.username} at time  {note.lastModified}"
        # Update other attributes of the note as needed
        note.save()

        # Update related Text object(s)
        text_data = request.POST['data']
        is_bold = request.POST.get('IsBold') == '1'
        is_italic = request.POST.get('IsItalic') == '1'
        is_underline = request.POST.get('IsUnderline') == '1'
        align = request.POST['align']
        style = request.POST['style']
        print(style)
        texts = Text.objects.filter(belong_to=note)
        for text in texts:
            text.data = text_data
            text.IsBold = is_bold
            text.IsItalic = is_italic
            text.IsUnderline = is_underline
            text.align = align
            text.style = style
            # Update other attributes of Text object as needed
            text.save()

        # Update related Media object
        media_type = request.POST.get("media_type")
        if media_type:
            details = request.FILES.get('details')
            if details:
                media_folder = os.path.join(settings.MEDIA_ROOT, 'medias')
                if not os.path.exists(media_folder):
                    os.makedirs(media_folder)

                media_path = os.path.join(media_folder, details.name)
                with open(media_path, 'wb+') as destination:
                    for chunk in details.chunks():
                        destination.write(chunk)

                # Create or update Media object
                Media.objects.create(media_type=media_type, details=os.path.join('medias', details.name), belong_to=note)

        # Update collaborator information
        error_messages = ""
        collaborator_names = request.POST.getlist('collaborator_name')
        collaborator_permissions = request.POST.getlist('collaborator_permission')
        for name, permission in zip(collaborator_names, collaborator_permissions):
            if name and permission:
                try:
                    collaborator_user = User.objects.get(username=name)
                    collaborator, created = collabs.objects.get_or_create(user_id=collaborator_user, note_id=note)
                    collaborator.permission = permission
                    collaborator.save()
                except User.DoesNotExist:
                    error_messages = f"User '{name}' does not exist."
                    return redirect('note:edit_note_form_m', note_id=note_id, error = error_messages)

    return redirect('note:view_notes')





@login_required
def delete_media(request, media_id):
    media = Media.objects.get(pk = media_id)
    media.delete()
    return redirect('note:view_notes')


@login_required
def delete_note(request, note_id):
    note = Note.objects.get(pk = note_id)
    note.delete()
    return redirect('note:view_notes')


@login_required
def delete_collab(request, c_id):
    c = collabs.objects.get(pk = c_id)
    c.delete()
    return redirect('note:view_notes')


@login_required
def create_notes(request):
    if request.method == 'POST':
        # Note
        title = request.POST['title']
        createdBy = request.user
        label = request.POST['label']
        version = 1
        lastModified = datetime.datetime.now()

ShareNote/note/templates/note/see_note.html
{% load custom_filters %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Note Details</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f8f8f8;
            color: #333;
        }

        .container {
            max-width: 800px;
            margin: 20px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .back-button {
            display: inline-block;
            margin-bottom: 20px;
            padding: 5px 10px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
        }

        .note-details {
            margin-bottom: 20px;
        }

        .note-title {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .note-label, .note-created-by, .media-heading, .content-heading, .collaborators-heading {
            margin-bottom: 10px;
        }

        .media-items, .note-content, .collaborators-list {
            border: 1px solid #ddd;
            padding: 10px;
            border-radius: 8px;
            margin-bottom: 20px;
        }

        .media-items img {
            max-width: 100%;
            height: auto;
            margin-top: 10px;
            border-radius: 8px;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
        }

        .media-pdf-link {
            display: block;
            margin-top: 10px;
            text-decoration: none;
            color: #007bff;
        }

        .content-item {
            margin-bottom: 10px;
        }

        .collaborator-item {
            margin-bottom: 5px;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="container">
        <a href="#" onclick="goBack()" style="text-decoration: none;" class="add-row-button">Back</a>
        <br><br>

        <div class="note-details">
            <h2 class="note-title">Title: {{ note.title }}</h2>
            <h3 class="note-label">Label: {{ note.label }}</h3>
            <h3 class="note-created-by">Created By: {{ note.createdBy }}</h3>
            <h3 class="note-created-by">Version: {{ note.version }}</h3>
        </div>

        <div class="note-content">
            <h3 class="content-heading">Content:</h3>
            {% for t in text %}
            <div style="{% if t.IsBold %} font-weight: bold; {% endif %}
                        {% if t.IsItalic %} font-style: italic; {% endif %}
                        {% if t.IsUnderline %} text-decoration: underline; {% endif %}
                        {% if t.align == 'Left-align' %} text-align: left; {% endif %}
                        {% if t.align == 'Right-align' %} text-align: right; {% endif %}
                        {% if t.align == 'Center-align' %} text-align: center; {% endif %}">
                        {{ t.data }} 
                </div>
            {% endfor %}
        </div>

        <div class="media-section">
            <h3 class="media-heading">Media:</h3>
            <div class="media-items"> 
                {% for m in media %}
                    {% if m.media_type == 'Image' %}
                        <img src="/notes/medias/{{ m.details|filename }}" alt="Image" style="height: 250px;">
                    {% elif m.media_type == 'PDF' %}
                        <a href="/notes/medias/{{ m.details|filename }}" target="_blank" class="media-pdf-link">{{ m.details|filename }}</a>
                    {% endif %}
                    <br><br>
                {% endfor %}
            </div>
        </div>

        <div class="template-section">
            <h3 class="template">Template:</h3>
            {% if note.templateUsed.title == 'Daily Schedule' %}
                <a href="{% url 'note:daily_schedule' note.id %}"><p>Template: {{ note.templateUsed.title }}</p></a>    
                <!-- <p>{{ note.templateUsed.content }}</p> -->
            {% elif note.templateUsed.title == 'To Do' %}
                <a href="{% url 'note:todo' note.id %}"><p>Template: {{ note.templateUsed.title }}</p></a>
            {% elif note.templateUsed.title == 'Week Schedule' %}
                <a href="{% url 'note:week_schedule' note.id %}"><p>Template: {{ note.templateUsed.title }}</p></a>
            {% endif %}
        </div>

        <div class="collaborators-section">
            <h3 class="collaborators-heading">Collaborators:</h3>
            <ul class="collaborators-list">
                {% for c in collab %}
                    <li class="collaborator-item">{{ c.user_id.username }} - {{ c.permission }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <script>
        function goBack() {
            window.history.back();
        }
    </script>
</body>
</html>

ShareNote/note/templates/note/view_note.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Notes</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>

<div class="container">
    <div class="header">
        <a href="{% url 'authApp:home' %}" class="create-note-btn">Home</a>
        <a href="{% url 'note:create_note_form' %}" class="create-note-btn">Create Note</a>
    </div>
    <hr>
    <div class="introduction">
        <h2>Welcome {{ request.user.username }}</h2>
        <p>This page allows you to view and manage your notes. You can navigate using the buttons below.</p>
    </div>
    {% if user_notes %}
        {% load custom_filters %}
        {% with labels=user_notes|extract_labels %}
            <div class="label-buttons">
                <h3>Labels:</h3>
                <button class="label-button" onclick="filterNotes('all')">All Notes</button>
                {% for label in labels %}
                    <!-- Generate a button for each label -->
                    <button class="label-button" onclick="filterNotes('{{ label }}')">{{ label }}</button>
                {% endfor %}
            </div>
            <ul>
                {% for note in user_notes %}
                    <div class="note" data-label="{{ note.label }}" style="display: none;">
                        <li style="list-style: none;">
                            <p class="note-title">Title: {{ note.title }}</p>
                            <!-- Template-specific content -->
                            {% if note.templateUsed.title == 'Daily Schedule' %}
                                <a href="{% url 'note:daily_schedule' note.id %}"><p>Template: {{ note.templateUsed.title }}</p></a>
                                <p>{{ note.templateUsed.content }}</p>
                            {% elif note.templateUsed.title == 'To Do' %}
                                <a href="{% url 'note:todo' note.id %}"><p>Template: {{ note.templateUsed.title }}</p></a>
                            {% elif note.templateUsed.title == 'Week Schedule' %}
                                <a href="{% url 'note:week_schedule' note.id %}"><p>Template: {{ note.templateUsed.title }}</p></a>
                            {% endif %}
                            <!-- Note content -->
                            <div class="note-content">
                                <h3>Content: </h3>
                                {% for text in note.text_set.all %}
                                    <div style="{% if text.IsBold %} font-weight: bold; {% endif %}
                                            {% if text.IsItalic %} font-style: italic; {% endif %}
                                            {% if text.IsUnderline %} text-decoration: underline; {% endif %}
                                            {% if text.align == 'Left-align' %} text-align: left; {% endif %}
                                            {% if text.align == 'Right-align' %} text-align: right; {% endif %}
                                            {% if text.align == 'Center-align' %} text-align: center; {% endif %}
                                            font-family : {{ text.style }}">
                                        {{ text.data }} 
                                    </div>
                                {% endfor %}
                            </div>
                            <!-- Media -->
                            <button class="media" onclick="mediaShow('{{ note.id }}')">Media</button>
                            <div class="mediaAll" style="display: none;" id="{{ note.id }}"> 
                                {% for media in note.media_set.all %}
                                    {% if media.media_type == 'Image' %}
                                        <img src="{{ media.details }}" alt="Image" style="height: 200px; margin-top: 20px;">
                                    {% elif media.media_type == 'PDF' %}
                                        <a href="{{ media.details }}" target="_blank">{{ media.details|filename }}</a>
                                    {% endif %}
                                    <form method="post" action="{% url 'note:delete_media' media.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="delete-media-btn" data-media-id="{{ media.id }}">Delete</button>
                                    </form>
                                    <br>
                                {% endfor %}
                            </div>
                            <!-- Collaborators -->
                            <button class="collab" onclick="collabShow('{{ note.id }}')">Show Collaborators</button>
                            <div class="collabsName" style="display: none;" id="{{ note.id }}">
                                <h3>Collaborators:</h3>
                                <ul>
                                    {% for collab in note.collabs_set.all %}
                                        <li>
                                            <strong>{{ collab.user_id.username }}</strong> - 
                                            {% if collab.permission == 'R' %}
                                                Read-only
                                            {% elif collab.permission == 'RW' %}
                                                Read and Write
                                            {% else %}
                                                {{ collab.permission }} Display permission value if neither R nor RW 
                                            {% endif %}
                                            <a href="{% url 'note:delete_collab' collab.id %}">delete</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <!-- Add Collaborators -->
                            <div>
                                <button class="addCollabs" onclick="collabForm('{{ note.id }}')">Add Collaborators</button>
                                <form method="post" action="{% url 'note:add_collabs' %}" class="collabForm" style="display: none;" onsubmit="return validateCollabs('{{ note.id }}')" id="{{note.id}}">
                                    {% csrf_token %}
                                    <input type="hidden" name="note_id" value="{{ note.id }}" />
                                    Enter collaborator name: <input type="text" class="collaboratorName" name="user_id" value="">
                                    <label for="permission">Permission:</label>
                                    <select name="permission" id="permission">
                                        <option value="None">Select permission</option>
                                        <option value="RW">Read and Write</option>
                                        <option value="R">Read-only</option>
                                    </select>
                                    <button type="submit">Add</button>
                                </form>
                            </div>
                            <!-- Edit/Delete Note -->
                            <div>
                                <br>
                                {% with error_message=" " %}
                                    <a href="{% url 'note:edit_note_form_m' note_id=note.id error=error_message %}">edit note</a> |
                                {% endwith %}
                                <a href="{% url 'note:delete_note' note.id %}">delete note</a>
                            </div>
                        </li>
                    </div>
                {% endfor %}
            </ul>
        {% endwith %}
    {% else %}
        <p>No notes available.</p>
        <p>Create your own notes with templates and customization...</p>
    {% endif %}
</div>

<div class="cn" style="display: none;">
    <h2>Your collab notes</h2>
    {% for note in collabs_notes %}
        {% for user in note.collabs_set.all %}
            <div class="note">
                <span style="font-weight: 900;">Title:</span> {{ note.title }}<br>
                <span style="font-weight: 900;">Created By:</span> {{ note.createdBy }}<br>
                <span style="font-weight: 900;">Permission:</span> {{ user.permission }}<br>
                {% if user.permission == 'RW' %}
                    <a href="{% url 'note:edit_note_form_c' note.id %}" >edit note</a> |
                    <a href="{% url 'note:see_perticular_note' note.id %}" >view note</a>
                {% elif user.permission == 'R' %}
                    <a href="{% url 'note:see_perticular_note' note.id %}" >view note</a> 
                {% endif %}
            </div>
        {% endfor %}
    {% endfor %}
</div>

<script>
    function collabShow(noteId) {
        var collab = document.querySelector('.collabsName[id="' + noteId + '"]');
        if (collab) {
            if (collab.style.display === "block") {
                collab.style.display = "none";
            } else {
                var collabs = document.querySelectorAll('.collabsName');
                collabs.forEach(function(collab) {
                    collab.style.display = "none";
                });
                collab.style.display = "block";
            }
        } else {
            console.error('Collab not found');
        }
    }

    function mediaShow(noteId) {
        var media = document.querySelector('.mediaAll[id="' + noteId + '"]');
        if (media) {
            if (media.style.display === "block") {
                media.style.display = "none";
            } else {
                var medias = document.querySelectorAll('.mediaAll');
                medias.forEach(function(media) {
                    media.style.display = "none";
                });
                media.style.display = "block";
            }
        } else {
            console.error('Media not found');
        }
    }

    function collabForm(noteId) {
        var form = document.querySelector('.collabForm[id="' + noteId + '"]');
        if (form) {
            if (form.style.display === "block") {
                form.style.display = "none";
            } else {
                var allForms = document.querySelectorAll('.collabForm');
                allForms.forEach(function(form) {
                    form.style.display = "none";
                });
                form.style.display = "block";
            }
        } else {
            console.error('Form not found');
        }
    }

    function validateCollabs(noteId) {
        var collaboratorName = document.querySelector('.collaboratorName[data-note-id="' + noteId + '"]').value;
        var users = [
            {% for user in users %}
                "{{ user.username }}",
            {% endfor %}
        ];
        var found = false;
        for (var i = 0; i < users.length; i++) {
            if (users[i] === collaboratorName) {
                found = true;
                document.querySelector('.collaboratorName[data-note-id="' + noteId + '"]').setAttribute("user_id", users[i]);
                break;
            }
        }
        if (!found) {
            alert("User " + collaboratorName + " is not present.");
            return false;
        }
        return true;
    }

    function filterNotes(label) {
        var notes = document.querySelectorAll('.note');
        var cn = document.querySelector('.cn');
        if (label === 'all') {
            notes.forEach(function(note) {
                note.style.display = 'block';
            });
            cn.style.display = 'block';
        } else {
            notes.forEach(function(note) {
                if (note.dataset.label === label) {
                    note.style.display = 'block';
                    cn.style.display = 'none';
                } else {
                    note.style.display = 'none';
                }
            });
        }
    }
</script>
</body>
</html>